baseURL = "https://hundhalsakunskap.se/"
title = "Hund Hälsa Kunskap"
DefaultContentLanguage = "sv"
languageCode = "sv"
enableRobotsTXT = true

[pagination]
  pagerSize = 6

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[permalinks]
  post = "/:year/:month/:slug/"
  page = "/:slug/"

[params]
  description = "Hundträning, hälsa och kunskap"
  images = ["img/enzo_webb–etta.jpg"]
  showPostSummary = true
  customDateFormat = "2006-01-02"
  themeColor = "skyblue"

[params.author]
  name = "Hund Hälsa Kunskap"

[params.social]
  instagram = "hundhalsakunskap"



[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
